### ISSUE TITLE
Website is not accessible. 

### ISSUE THREAD

**Issue by c4milo** [node-xmpp/node-xmpp#283] opened 2015-09-11 17:31 UTC
https://cloudup.com/cMZMM32ZP2D

**Comment by sonnyp** [comment] 2015-09-11 17:33
sorry about that will fix this weekend.

duplicate of duplicate https://github.com/node-xmpp/node-xmpp.github.io/issues/11

**Closed by sonnyp** 2015-09-11 17:33 UTC

**Comment by sonnyp** [comment] 2015-09-21 14:44
fixed, sorry for the delay

**Comment by c4milo** [comment] 2015-09-21 15:06
no problem, thank you!
